apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
data:
    {{- toYaml .Values.data | nindent 12 }}
