kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-pv-volume
  namespace: {{ .Values.app.namespace }}
  labels:
    type: local
    app: {{ .Values.app.name }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi