app:
  name: analytics-service
  namespace: kafka
  environment: dev
  owner: vitalii.rubezhanskii@gmail.com

image:
  repository: vitalii1992/analytics-service
  tag: latest

replicaCount: 1
imagePullPolicy: Always

service:
  type: LoadBalancer
  externalIP: 192.168.64.8

ports:
  - name: http
    value: 8080

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

liveness:
  initialDelaySeconds: 10
  port: http
  path: /actuator/health/liveness
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 3
  periodSeconds: 5

readiness:
  initialDelaySeconds: 10
  port: http
  path: /actuator/health/readiness
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 3
  periodSeconds: 5

envs:
  - name: SPRING_PROFILES_ACTIVE
    value: deployment

application:
  spring:
    cloud:
      stream:
        function.definition: "process"
        bindings:
          process-in-0:
            destination: "quote"
          process-out-0:
            destination: "quote-aggregation"
            producer:
              useNativeEncoding: "true"
        kafka:
          binder:
            brokers: "my-kafka-cluster-kafka-bootstrap:9092"
          bindings:
            process-in-0:
              consumer:
                configuration:
                  schema.registry.url: "http://strimzi-registry-operator:8081"
                  key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
                  value.deserializer: com.investment.serializer.SensorDeserializer
            process-out-0:
              producer:
                configuration:
                  schema.registry.url: "http://strimzi-registry-operator:8081"
                  key.serializer: org.apache.kafka.common.serialization.StringSerializer
                  value.serializer: com.investment.serializer.SensorSerializer
          streams:
            binder:
              brokers: "my-kafka-cluster-kafka-bootstrap:9092"
            configuration:
              schema.registry.url: "http://strimzi-registry-operator:8081"
            specific.avro.reader: "true"
            bindings:
              process-out-0:
                producer:
                  keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                  valueSerde: com.investment.serde.SensorSerde
              process-in-0:
                consumer:
                  keySerde: org.apache.kafka.common.serialization.Serdes$StringSerde
                  valueSerde: com.investment.serde.SensorSerde
  security.basic.enabled: "false"
  server.port: "9998"
