app:
  name: analytics-service
  namespace: kafka
  environment: dev
  owner: vitalii.rubezhanskii@gmail.com

image:
  repository: vitalii1992/analytics-service
  tag: latest

replicaCount: 1
imagePullPolicy: Always

service:
  type: LoadBalancer
  externalIP: 192.168.64.8

ports:
  - name: http
    value: 8080

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

liveness:
  initialDelaySeconds: 10
  port: http
  path: /actuator/health/liveness
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 3
  periodSeconds: 5

readiness:
  initialDelaySeconds: 10
  port: http
  path: /actuator/health/readiness
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 3
  periodSeconds: 5

envs:
  - name: SPRING_PROFILES_ACTIVE
    value: deployment
