app:
  name: api-gateway-service
  namespace: kafka
  environment: dev
  owner: vitalii.rubezhanskii@gmail.com

image:
  repository: vitalii1992/api-gateway-service
  tag: latest

replicaCount: 1
imagePullPolicy: Always

service:
  type: LoadBalancer
  externalIP: 192.168.64.8

ports:
  - name: http
    value: 8080

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

liveness:
  initialDelaySeconds: 10
  port: http
  path: /actuator/health/liveness
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 3
  periodSeconds: 5

readiness:
  initialDelaySeconds: 10
  port: http
  path: /actuator/health/readiness
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 3
  periodSeconds: 5

envs:
  - name: SPRING_PROFILES_ACTIVE
    value: deployment

application:
  spring:
    cloud:
      gateway:
        discovery:
          locator:
            enabled: true
        default-filters:
          - TokenRelay
        routes:
          - id: account
            uri: lb://account
            predicates:
              - Path=/account/**
            filters:
              - RewritePath=/account/(?<path>.*), /$\{path}
          - id: order
            uri: lb://order
            predicates:
              - Path=/order/**
            filters:
              - RewritePath=/order/(?<path>.*), /$\{path}
    security:
      oauth2:
        client:
          registration:
            keycloak-spring-gateway-client:
              provider: "my-keycloak-provider"
              scope: "openid"
              client-id: "spring-gateway-client"
              client-secret: "3RhEF8pqKTANrQ6BhfxaYVmcjTXsDK0u"
              authorization-grant-type: "authorization_code"
              redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
          provider:
            my-keycloak-provider:
              issuer-uri: "http://192.168.64.8:31760/auth/realms/My-Realm"
              jwk-set-uri: "http://192.168.64.8:31760/auth/realms/My-Realm/protocol/openid-connect/certs"
              authorization-uri: "http://192.168.64.8:31760/auth/realms/My-Realm/protocol/openid-connect/auth"

  security.basic.enabled: "false"
  server.port: "8080"
